// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\spike\GolandProjects\lora_esp_gsm_gps_project\internal\core\interfaces.go

// Package core is a generated GoMock package.
package core

import (
	core "Lora_Esp_Gsm_Gps_project/internal/core"
	models "Lora_Esp_Gsm_Gps_project/internal/models"
	context "context"
	sql "database/sql"
	net "net"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// FindById mocks base method.
func (m *MockRepository) FindById(ctx context.Context, id int) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", ctx, id)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockRepositoryMockRecorder) FindById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockRepository)(nil).FindById), ctx, id)
}

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// ProcessData mocks base method.
func (m *MockService) ProcessData(data interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessData", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessData indicates an expected call of ProcessData.
func (mr *MockServiceMockRecorder) ProcessData(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessData", reflect.TypeOf((*MockService)(nil).ProcessData), data)
}

// MockApp is a mock of App interface.
type MockApp struct {
	ctrl     *gomock.Controller
	recorder *MockAppMockRecorder
}

// MockAppMockRecorder is the mock recorder for MockApp.
type MockAppMockRecorder struct {
	mock *MockApp
}

// NewMockApp creates a new mock instance.
func NewMockApp(ctrl *gomock.Controller) *MockApp {
	mock := &MockApp{ctrl: ctrl}
	mock.recorder = &MockAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApp) EXPECT() *MockAppMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockApp) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockAppMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockApp)(nil).Close))
}

// GetDB mocks base method.
func (m *MockApp) GetDB() *sql.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDB")
	ret0, _ := ret[0].(*sql.DB)
	return ret0
}

// GetDB indicates an expected call of GetDB.
func (mr *MockAppMockRecorder) GetDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDB", reflect.TypeOf((*MockApp)(nil).GetDB))
}

// GetRepo mocks base method.
func (m *MockApp) GetRepo() core.Repository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepo")
	ret0, _ := ret[0].(core.Repository)
	return ret0
}

// GetRepo indicates an expected call of GetRepo.
func (mr *MockAppMockRecorder) GetRepo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepo", reflect.TypeOf((*MockApp)(nil).GetRepo))
}

// GetService mocks base method.
func (m *MockApp) GetService() core.Service {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetService")
	ret0, _ := ret[0].(core.Service)
	return ret0
}

// GetService indicates an expected call of GetService.
func (mr *MockAppMockRecorder) GetService() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetService", reflect.TypeOf((*MockApp)(nil).GetService))
}

// MockMeasurementHandler is a mock of MeasurementHandler interface.
type MockMeasurementHandler struct {
	ctrl     *gomock.Controller
	recorder *MockMeasurementHandlerMockRecorder
}

// MockMeasurementHandlerMockRecorder is the mock recorder for MockMeasurementHandler.
type MockMeasurementHandlerMockRecorder struct {
	mock *MockMeasurementHandler
}

// NewMockMeasurementHandler creates a new mock instance.
func NewMockMeasurementHandler(ctrl *gomock.Controller) *MockMeasurementHandler {
	mock := &MockMeasurementHandler{ctrl: ctrl}
	mock.recorder = &MockMeasurementHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMeasurementHandler) EXPECT() *MockMeasurementHandlerMockRecorder {
	return m.recorder
}

// GetAllSessions mocks base method.
func (m *MockMeasurementHandler) GetAllSessions() ([]models.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllSessions")
	ret0, _ := ret[0].([]models.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllSessions indicates an expected call of GetAllSessions.
func (mr *MockMeasurementHandlerMockRecorder) GetAllSessions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllSessions", reflect.TypeOf((*MockMeasurementHandler)(nil).GetAllSessions))
}

// GetMeasurements mocks base method.
func (m *MockMeasurementHandler) GetMeasurements(requestID int) ([]models.Packet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMeasurements", requestID)
	ret0, _ := ret[0].([]models.Packet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMeasurements indicates an expected call of GetMeasurements.
func (mr *MockMeasurementHandlerMockRecorder) GetMeasurements(requestID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMeasurements", reflect.TypeOf((*MockMeasurementHandler)(nil).GetMeasurements), requestID)
}

// ProcessInterfaceSettingChange mocks base method.
func (m *MockMeasurementHandler) ProcessInterfaceSettingChange(conn net.Conn, msg string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessInterfaceSettingChange", conn, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessInterfaceSettingChange indicates an expected call of ProcessInterfaceSettingChange.
func (mr *MockMeasurementHandlerMockRecorder) ProcessInterfaceSettingChange(conn, msg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessInterfaceSettingChange", reflect.TypeOf((*MockMeasurementHandler)(nil).ProcessInterfaceSettingChange), conn, msg)
}

// ProcessPacketData mocks base method.
func (m *MockMeasurementHandler) ProcessPacketData(msg string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessPacketData", msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessPacketData indicates an expected call of ProcessPacketData.
func (mr *MockMeasurementHandlerMockRecorder) ProcessPacketData(msg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessPacketData", reflect.TypeOf((*MockMeasurementHandler)(nil).ProcessPacketData), msg)
}

// RemoveSession mocks base method.
func (m *MockMeasurementHandler) RemoveSession(sessionId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveSession", sessionId)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveSession indicates an expected call of RemoveSession.
func (mr *MockMeasurementHandlerMockRecorder) RemoveSession(sessionId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveSession", reflect.TypeOf((*MockMeasurementHandler)(nil).RemoveSession), sessionId)
}

// SaveSession mocks base method.
func (m *MockMeasurementHandler) SaveSession(session models.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSession", session)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSession indicates an expected call of SaveSession.
func (mr *MockMeasurementHandlerMockRecorder) SaveSession(session interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSession", reflect.TypeOf((*MockMeasurementHandler)(nil).SaveSession), session)
}

// SendAllSessions mocks base method.
func (m *MockMeasurementHandler) SendAllSessions(conn net.Conn, data string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendAllSessions", conn, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendAllSessions indicates an expected call of SendAllSessions.
func (mr *MockMeasurementHandlerMockRecorder) SendAllSessions(conn, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAllSessions", reflect.TypeOf((*MockMeasurementHandler)(nil).SendAllSessions), conn, data)
}

// SendMeasurementCommand mocks base method.
func (m *MockMeasurementHandler) SendMeasurementCommand(conn net.Conn, command string, sessionId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMeasurementCommand", conn, command, sessionId)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMeasurementCommand indicates an expected call of SendMeasurementCommand.
func (mr *MockMeasurementHandlerMockRecorder) SendMeasurementCommand(conn, command, sessionId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMeasurementCommand", reflect.TypeOf((*MockMeasurementHandler)(nil).SendMeasurementCommand), conn, command, sessionId)
}

// SendMeasurementsToClient mocks base method.
func (m *MockMeasurementHandler) SendMeasurementsToClient(conn net.Conn, command string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMeasurementsToClient", conn, command)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMeasurementsToClient indicates an expected call of SendMeasurementsToClient.
func (mr *MockMeasurementHandlerMockRecorder) SendMeasurementsToClient(conn, command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMeasurementsToClient", reflect.TypeOf((*MockMeasurementHandler)(nil).SendMeasurementsToClient), conn, command)
}
